// Generated by CoffeeScript 1.8.0
(function() {
  var BrowserWindow, app;

  app = require('app');

  BrowserWindow = require('browser-window');

  require('crash-reporter').start();

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      return app.quit();
    }
  });

  app.on('ready', function() {
    var dialog, height, ipc, mainWindow, output_directory, width;
    width = 300 + 10 * 2 + 10 * 2;
    height = width + 5 + 50;
    mainWindow = new BrowserWindow({
      width: width,
      height: height,
      resizable: false,
      center: true,
      show: false
    });
    dialog = require('dialog');
    ipc = require('ipc');
    output_directory = null;
    ipc.on('output-setting', function() {
      return dialog.showOpenDialog({
        title: 'Choose output directory',
        properties: ['openDirectory']
      }, function(directories) {
        if (directories && directories.length > 0) {
          output_directory = directories[0];
        } else {
          output_directory = null;
        }
        return mainWindow.webContents.send('output-seted', output_directory);
      });
    });
    ipc.on('icon-droped', function(event, path) {
      var args, ext, icons, spawn;
      ext = path.split('.').pop().toLowerCase();
      if (ext !== 'png' && ext !== 'jpg' && ext !== 'jpeg' && ext !== 'bmp') {
        return;
      }
      spawn = require('child_process').spawn;
      args = [path];
      if (output_directory) {
        args.push('-o');
        args.push(output_directory);
      }
      icons = spawn('icons', args);
      icons.stdout.on('data', function(data) {
        return console.log('stdout: ' + data);
      });
      icons.stderr.on('data', function(data) {
        return console.log('stderr: ' + data);
      });
      icons.on('exit', function(code) {
        if (code === 0) {
          return dialog.showMessageBox({
            type: 'info',
            buttons: ['OK'],
            title: 'Success',
            message: 'Your icons is ready to go'
          });
        }
      });
      return icons.unref();
    });
    mainWindow.loadUrl('file://' + __dirname + '/index.html');
    mainWindow.webContents.on('did-finish-load', function() {
      return mainWindow.show();
    });
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  });

}).call(this);
